### ISSUE TITLE
Build of benchmark test fails with gcc 14.2.0

### ISSUE THREAD

**Issue by rod-chapman** [pq-code-package/mlkem-native#552]
I try to run the benchmarks test on macOS using gcc 14.2.0, I get:

```
$ tests bench -r -c M1
INFO  > Benchmark          Compile     (native, no_opt) make CROSS_PREFIX= bench CYCLES=M1 AUTO=1 OPT=0
test/hal/hal.c: In function ‘init_rdtsc’:
test/hal/hal.c:250:10: error: ISO C forbids conversion of object pointer to function pointer type [-Werror=pedantic]
  250 |   name = (name##proc *)(dlsym(kperf, #name)); \
      |          ^
test/hal/hal.c:159:3: note: in expansion of macro ‘F’
  159 |   F(int, kpc_get_counting, void)               \
      |   ^
test/hal/hal.c:256:3: note: in expansion of macro ‘KPERF_LIST’
  256 |   KPERF_LIST
      |   ^~~~~~~~~~
```

Same thing using Apple's default /usr/bin/gcc (which is actually clang 16.0.0) works fine.

**Comment by hanno-becker** [comment]
Thanks @rod-chapman , what exact steps did you do?

**Comment by hanno-becker** [comment]
This is a known issue https://pubs.opengroup.org/onlinepubs/009695399/functions/dlsym.html

**Comment by rod-chapman** [comment]
That proposed change doesn't work, since the conversion to (void *) in the printf() call is then illegal for the same reason. I will try the pragma.

**Comment by rod-chapman** [comment]
This appears to work and it compiles OK with both clang 16 and gcc 14.2.0 on my Mac:
```
/* Temporarily disable -Wpedantic here to allow conversion
 * from (void *) to function-pointer.
 */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpedantic"

#define F(ret, name, ...)                     \
  name = (name##proc *)(dlsym(kperf, #name)); \
  if (!name)                                  \
  {                                           \
    printf("%s = %p\n", #name, (void *)name); \
    return;                                   \
  }
  KPERF_LIST
#undef F

```
